### ISSUE TITLE
Ruby+gem updates cause error Sketch Maps-view

### ISSUE THREAD

**Issue by Jiskahuizing** [Jiskahuizing/torn-tracks#41]
After updating to ruby version 2.6.3 (from 2.4.0) + updating gems (see attached gemfile, which is the updated version), the lines and tracks aren't visible anymore on the Sketch Maps-view of the website.

The information is loaded on the page, visible in the terminal and through the development tools on the page itself, but is not displayed, with the TimeKnot-lines that should appear.

[Gemfile.lock NEW.docx](https://github.com/Jiskahuizing/torn-tracks/files/3697026/Gemfile.lock.NEW.docx)

**Comment by nynnejc** [comment]
This can be closed! Thanks to Dennis'help we discovered the culprit was the d3-rails gem that was raising havoc when updated. When updated from version 5.7.0 to 5.9.2, the gem just failed silently and thereby ruined the sketch maps view I now updated everything else and will try to see if I can then also update the d3-rails gem now that everything is in newer versions, who knows it might work with Rails version 6? Will let you know but I'm closing this issue now.
